  version : "3"
  services:

    eureka-service:
      image: eurekaservice-app
      build: spring-eureka-server/
      restart: always
      network_mode: host
      container_name: eureka-service-docker
      ports:
        - "8761:8761"
      expose:
        - 8761

    mongo:
      image: mongo
      ports:
        - "27017:27017"
      container_name: mongo
      network_mode: host

    spring-config-server:
      image: configservice-app
      build: Config-Server/
      restart: always
      network_mode: host
      container_name: config-service
      ports:
        - "8888:8888"
      expose:
        - 8888
    api-gateway-service:
      image: apigatewayservice-app
      build: spring-boot-zuulgatewayproxy/
      restart: always
      network_mode: host
      container_name: apigateway-service-docker
      ports:
        - "8090:8090"
      expose:
        - 8090
    muzizapplication:
      image: trackservice-app
      build: muzixApp/
      restart: always
      network_mode: host
      container_name: track-service-docker
      depends_on:
        - mongo
        - spring-config-server
        - eureka-service
      ports:
        - "8083:8083"
      expose:
        - 8083
    user-profile:
      image: userservice-app
      build: User Service/
      restart: always
      network_mode: host
      container_name: user-service-docker
      depends_on:
        - mongo
        - spring-config-server
        - eureka-service
      ports:
        - "8082:8082"
      expose:
        - 8082